---
bot:
  debug_commands: false
  max_retries: 10
  # Minutes
  skip_message_time: 30
  thread_pool_size: 10
  token: YOUR_BOT_TOKEN_HERE
cache:
  # Minutes
  default_ttl: 30
database:
  file: data/db.sqlite3
dev_bot:
  admin_chat_id: YOUR_ADMIN_CHAT_ID_HERE
  enabled: false
  token: YOUR_DEV_BOT_TOKEN_HERE
image_generator:
  height: 1200
  width: 1400
parser:
  browser:
    headless: true
    threaded: true
  fetch_schedule_with_browser: false
  fetch_teacher_schedule_with_browser: true
  max_retries: 1
  timeout: 15